try {
  fucntioindfsf()
} catch(ex) {
  console.log('error' + ex)
}
